const { chromium } = require('playwright');
const { expect } = require('playwright/test');
const assert = require('node:assert/strict');
const { spawn, execFileSync } = require('node:child_process');
const path = require('node:path');
const fs = require('node:fs');
const readline = require('node:readline');
const root = path.resolve(__dirname, '..');
const python = process.env.PYTHON || path.join(root, 'dev-venv/bin/python');
const fixture = path.join(__dirname, 'board_live_server.py');
(async () => {
  const server = spawn(python, ['-u', fixture], { cwd: root, stdio: ['pipe', 'pipe', 'pipe'] });
  let log = '', browser, info;
  server.stderr.on('data', data => { log += data; });
  try {
    info = await new Promise((resolve, reject) => {
      const timer = setTimeout(() => reject(new Error(log || 'Fixture timeout')), 15000);
      readline.createInterface({ input: server.stdout }).once('line', line => { clearTimeout(timer); resolve(JSON.parse(line)); });
      server.once('error', reject);
    });
    browser = await chromium.launch();
    const page = await browser.newPage({ viewport: { width: 1357, height: 806 } });
    const errors = [];
    page.on('pageerror', e => errors.push(e.message));
    await expect.poll(async () => {
      try { return (await page.request.get(info.url + '/health')).status(); } catch (_) { return 0; }
    }).toBe(200);
    await page.goto(info.url + '/settings?section=tasks');
    await expect(page.locator('#init_script_timeout')).toHaveValue('300');
    await expect(page.locator('#init_script_path')).toHaveClass('input-big');
    await expect(page.locator('#base_dir')).toBeVisible();
    await expect(page.locator('#base_dir')).toHaveAttribute('required', '');
    await page.locator('#base_dir').fill('/remote/tasks');
    await page.locator('#init_script_text').fill('  echo hello\n\n');
    await page.getByRole('button', { name: 'Save', exact: true }).click();
    await expect(page.locator('.toast')).toContainText('Saved successfully');
    await page.reload();
    await expect(page.locator('#init_script_text')).toHaveValue('  echo hello\n\n');
    await expect(page.locator('#base_dir')).toHaveValue('/remote/tasks');
    await page.locator('#init_script_path').fill('~/init.sh');
    await page.getByRole('button', { name: 'Save', exact: true }).click();
    await expect(page.locator('.toast[role=alert]')).toContainText('either path or text');
    const settings = JSON.parse(fs.readFileSync(path.join(info.directory, 'settings/tasks.json'), 'utf8'));
    assert.equal(settings.init_script_path, '');
    let gate, arrived;
    const received = new Promise(resolve => { arrived = resolve; });
    await page.route('**/api/settings/tasks', async route => { await new Promise(resolve => { gate = resolve; arrived(); }); await route.continue(); });
    await page.locator('#init_script_text').fill('');
    await page.getByRole('button', { name: 'Save', exact: true }).click();
    await received;
    await expect(page.locator('#settings-form')).toHaveAttribute('aria-busy', 'true');
    await expect(page.locator('#init_script_path')).toBeDisabled();
    gate();
    await expect(page.getByRole('button', { name: 'Save', exact: true })).toBeEnabled();
    await expect(page.locator('.toast[role=alert]').last()).toContainText('remote server unavailable');
    await page.unroute('**/api/settings/tasks');
    await page.locator('#init_script_path').fill('');
    if (process.env.CYCLE_SCREENSHOTS) await page.screenshot({ path: process.env.CYCLE_SCREENSHOTS + '-settings.png', fullPage: true });
    await page.setViewportSize({ width: 375, height: 806 });
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.setViewportSize({ width: 1875, height: 850 });
    const create = await page.request.post(info.url + '/api/board/tasks', { multipart: { task_id: 'INIT-1', title: 'Initialize task workspace', description: 'Run Init before the agent' } });
    assert.equal(create.status(), 201);
    await page.request.patch(info.url + '/api/board/tasks/INIT-1/move', { data: { status: 'OPEN', position: 0 } });
    await page.goto(info.url);
    const card = page.locator('.task-card[data-task-id="INIT-1"]');
    const operation = (name, id) => JSON.parse(execFileSync(python, [fixture, '--directory', info.directory, '--operation', name, ...(id ? ['--run-id', id] : [])], { cwd: root, encoding: 'utf8' }));
    const run = operation('claim');
    await expect(card.locator('.task-extra-status')).toHaveText('In progress');
    operation('init', run.id);
    await expect(card.locator('.task-extra-status')).toHaveText('Init');
    if (process.env.CYCLE_SCREENSHOTS) await page.screenshot({ path: process.env.CYCLE_SCREENSHOTS + '-board.png', fullPage: true });
    operation('agent', run.id);
    await expect(card.locator('.task-extra-status')).toHaveText('Agent');
    operation('init-failure', run.id);
    await expect(page.locator('.board-column[data-status="WAIT"]').locator('.task-card')).toBeVisible();
    await expect(card).toHaveClass(/is-error/);
    await expect(card.locator('.task-extra-status')).toHaveCount(0);
    await expect(card.locator('.task-card-bar')).toHaveCSS('background-color', 'rgb(241, 91, 91)');
    await card.click();
    const body = page.locator('.chat-message-body');
    await expect(body).toHaveText('Init script error: <img src=x onerror=alert(1)>');
    await expect(body.locator('img')).toHaveCount(0);
    await expect(page.locator('.chat-message-time')).toHaveText(/\d{4}-\d\d-\d\d \d\d:\d\d/);
    await page.locator('#chat-comment').fill('Fixed the script; retry');
    await page.locator('#send-comment').click();
    await expect(page.locator('.chat-user')).toBeVisible();
    const retry = operation('claim');
    operation('agent', retry.id);
    operation('message', retry.id);
    operation('success', retry.id);
    await expect(body).toHaveCount(3);
    await expect(body.first()).toHaveText('Init script error: <img src=x onerror=alert(1)>');
    await expect(body.last()).toHaveText('Agent response after retry');
    await expect(page.locator('#chat-composer')).toBeVisible();
    if (process.env.CYCLE_SCREENSHOTS) await page.screenshot({ path: process.env.CYCLE_SCREENSHOTS + '-chat.png', fullPage: true });
    assert.deepEqual(errors, []);
    console.log('PASS: Tasks settings, save validation/Spinner, mobile layout, live phases, red WAIT card, text-only Init error and persistent retry history');
  } finally {
    if (browser) await browser.close();
    const exited = new Promise(resolve => server.once('exit', resolve));
    server.stdin.end('\n');
    const timer = setTimeout(() => server.kill('SIGKILL'), 10000);
    await exited;
    clearTimeout(timer);
    if (info) assert.equal(fs.existsSync(info.directory), false);
  }
})().catch(e => { console.error(e); process.exitCode = 1; });
